# Generated by Django 2.2.3 on 2019-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basework',
            name='category',
            field=models.CharField(blank=True, choices=[('ds', 'Designing'), ('wb', 'Web Development'), ('md', 'Medics'), ('ag', 'Agricultural'), ('sa', 'Sys Admin')], max_length=2, null=True),
        ),
    ]
