# Generated by Django 2.2.3 on 2019-07-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190720_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
