# Generated by Django 2.2.3 on 2019-07-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='works.Job'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='works.Quest'),
        ),
    ]
